development:
  adapter: postgresql
  encoding: unicode
  database: streamable_dev
  pool: 5
  username: <%= `whoami` %>
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: streamable_test
  pool: 5
  username: <%= `whoami` %>
  password:
